---
version: '3.7'

services:

  mocha:
    build:
      context: .
    command: mocha /project/src/nightwatch/*.test.js --reporter mochawesome
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./results/nightwatch/mochawesome-report/:/project/tests/src/mochawesome-report/

